{% set name = "azure-mgmt-imagebuilder" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: e2b12dcd024cd55edf231a9ebc2645afc466a3b2e6cc8779fa161956fb86875f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - setuptools
    - wheel
    - python
    - pip
  run:
    - python
    - isodate >=0.6.1,<1.0.0
    - azure-mgmt-core >=1.6.0
    - typing-extensions >=4.6.0

# Azure sdk test tools are not supported by pypi and Anaconda.
# Only pip check is performed.
test:
  imports:
    - azure.mgmt.imagebuilder
    - azure.mgmt.imagebuilder.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Image Builder Client Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: |
    This is the Microsoft Azure Image Builder Management Client Library.
  doc_url: https://github.com/Azure/azure-sdk-for-python
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
